### ISSUE TITLE
SNES doesn't power on after Multiregion board install

### ISSUE THREAD

**Issue by shawly** [borti4938/SNES-AddOn-PCBs#10] opened 2019-12-18 18:24 UTC
I got myself a PCB for my 2chip from David from oldskoolconsoles. 
After the install my SNES wouldn't turn on anymore, so I unsoldered the PCB to make sure the SNES itself isn't dead, after I removed the PCB it powered on again, so there must be an issue with the board itself.
I checked and insulated the motherboard of my 2chip to make sure there were no shorts and installed the PCB again, to no avail since the SNES didn't power on again after the re-installation.
I've checked everything, made sure that I didn't bridge both LED jumpers and I've tried both soldering a wire to pad 7 aswell as bridging the jumper for sCIC to no avail...

It seems like the board is dead (or there was an issue in production), do you have any ideas what else I could check for or could've gone wrong?
I took some pictures aswell, maybe I made an obvious mistake: https://imgur.com/a/pLSpxnl

**Comment by borti4938** [comment] 2019-12-18 20:58
I didn't see anything wrong in your picture. Maybe just be careful with the wire routing around the mainboard. They might be squeezed between mainboard and RF shield (and break or shorted to GND consequentially) especially if you apply light preasure to the screws.
However, most of the time - out of my experience - a black screen after installation is caused by cold solder joints. Heat capacity of the cartridge slot is quite high, so you have to be patient on soldering the board to the pins (lot of heat, long time duration) such that the solder makes good connection to the slot pins.

On DIY PCBs there is sometimes also a bad connection on any of the ICs pins, which may cause an issue too depending on the signal at the particular pin.

So everything I can recommend is tripple check everything once again. If nothing helps, please reach out to oldskoolconsoles as they sold the PCB to you. There might be a problem with any IC on the board. Checking those would require to desolder and test them.

As this is not an issue with the board design, I close the issue for the moment. I hope you understand; however you should be able to leave a comment anyway.

**Closed by borti4938** 2019-12-18 20:58 UTC

**Comment by shawly** [comment] 2019-12-19 08:48
Thanks for the answer borti! 

> They might be squeezed between mainboard and RF shield (and break or shorted to GND consequentially) especially if you apply light preasure to the screws.

I haven't put on the RF shield for testing so that is probably not an issue. I also don't get a black screen, the SNES doesn't get **any power** whatsoever, LEDs won't turn on aswell as my SD2SNES won't get power.

> Heat capacity of the cartridge slot is quite high, so you have to be patient on soldering the board to the pins (lot of heat, long time duration) such that the solder makes good connection to the slot pins.

I thought I applied enough heat to the cartridge slot pins, but my best bet is to try again since I can't do anything else than to wait for the answer from oldskoolconsoles anyway.

> As this is not an issue with the board design, I close the issue for the moment. I hope you understand; however you should be able to leave a comment anyway.

Of course, I just thought asking you might be my best bet on troubleshooting. 
Thank you very much for your help!
